chat/urls.py
from django.urls import path

from . import views


app_name = "chat"

urlpatterns = [
    # ex: 127.0.0.1/chat/
    path("", views.index, name="chat-index"),
    # ex: 127.0.0.1/chat/chatter
    path("chatter", views.chatter, name="chatter")
]

dj4me_project/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # ex: 127.0.0.1/
    path('', TemplateView.as_view(
        template_name='games/main_index.html'), name='main-index'),
    # ex: 127.0.0.1/games
    path("games/", include("games.urls")),
    # ex: 127.0.0.1/chat
    path("chat/", include("chat.urls")),
    # ex: 127.0.0.1/admin
    path("admin/", admin.site.urls),
]

games/urls.py
from django.urls import path

from . import views


app_name = "games"

urlpatterns = [
    path("", views.index, name="games-index"),
]

chat/models.py
from django.db import models

# Create your models here.

chat/views.py
from django.shortcuts import render
from dj4me_project.settings import OAI_API_KEY
import json
import requests
# Create your views here.


def send_text_message(message):
    headers = {'Content-Type': 'application/json',
               'Authorization': f'Bearer {OAI_API_KEY}', }
    payload = json.dumps({
        "model": "text-davinci-003",
        "prompt": message
    })
    r = requests.post('https://api.openai.com/v1/completions',
                      headers=headers, data=payload)

    response_content_dict = json.loads(r.content)
    response_text = response_content_dict.get('choices')[0].get('text')
    return response_text.strip()


def send_chat_message(message):
    headers = {'Content-Type': 'application/json',
               'Authorization': f'Bearer {OAI_API_KEY}', }
    payload = json.dumps({
        "model": "gpt-3.5-turbo",
        "messages": [{"role": "user", "content": message, "name": "serg"}]
    })
    r = requests.post('https://api.openai.com/v1/chat/completions',
                      headers=headers, data=(payload))

    resp_content_di = json.loads(r.content)
    content = resp_content_di.get('choices')[0].get('message').get('content')
    return content


def index(request):
    return render(request, "chat/index.html")


def chatter(request):
    if not request.POST.get('user_message'):
        ctx = {"message_response": "Please enter your message!"}
    else:
        msg = request.POST.get('user_message')
        msg_response = send_chat_message(msg)
        ctx = {"message_response": msg_response}
    return render(request, "chat/chatter.html", context=ctx)

games/views.py
from django.shortcuts import render
# from django.http import HttpResponse

# def index(request):
    # return HttpResponse("Hello, world. You're at the polls index.")

def index(request):
    return render(request, "games/index.html") 

chat/templates/chat/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Custom CSS -->
    <!-- <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}"> -->

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"
        defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"
        defer></script>

    {% block title %}{% endblock title %}
</head>
<body>
    {% block navbar %}
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'chat:chat-index' %}">Chat Home</a>
          <button aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
            data-target="#navbarToggle" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="navbar-brand mr-4" href="{% url 'chat:chatter' %}">ChatAI</a>
              <a class="nav-item nav-link" href="{% url 'games:games-index' %}">Games</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="#">Login</a>
              <a class="nav-item nav-link" href="#">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    {% endblock navbar %}
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

chat/templates/chat/chatter.html
{% extends "chat/base.html" %}

{% block title%}
<title>Chat Page</title>
{% endblock title %}

{% block content %}
<h1>Chat with me</h1>

<p>{{ message_response }}</p>
<form action="{% url 'chat:chatter' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <!-- <input type="text" name="user_message" id="1" placeholder="Enter your message" required> -->
        <textarea name="user_message" id="1" cols="30" rows="10"></textarea>
        <label for="1">Message</label><br>
    </fieldset>
    <input type="submit" value="Send Message">
</form>
{% endblock content %}

chat/templates/chat/index.html
{% extends "chat/base.html" %}

{% block title%}
<title>Chat App</title>
{% endblock title %}

{% block content %}

<body>
    <h1>Hello! Nice to see you!</h1>

    <h3>As an AI language model, I work by processing large amounts of data and learning to recognize patterns and
        relationships between words and concepts. When a user inputs a question or prompt, I analyze the sentence
        structure, identify keywords, and use algorithmic rules to generate an appropriate response. My responses are
        based on the data I have been trained on and the context of the user's input. I can provide information on a
        wide range of topics, perform language translation, and even generate original content like poems and stories.
        Overall, my functionality is based on advanced machine learning and natural language processing techniques,
        which allow me to understand and respond to human language with increasing accuracy and complexity. </h3>
</body>
{% endblock content %}

games/templates/games/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Custom CSS -->
    <!-- <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}"> -->

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"
        defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"
        defer></script>

    {% block title %}{% endblock title %}
</head>
<body>
    {% block navbar %}
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'games:games-index' %}">Games Home</a>
          <button aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
            data-target="#navbarToggle" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'games:games-index' %}">Games</a>
              <a class="navbar-brand mr-4" href="{% url 'chat:chat-index' %}">Chat App</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="#">Login</a>
              <a class="nav-item nav-link" href="#">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    {% endblock navbar %}
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

games/templates/games/index.html
{% extends "games/base.html" %}

{% block title%}
    <title>Games Page</title>
{% endblock title %}

{% block content %}
    <h1>Games Page</h1>
    <p>Page is under development</p>
    <p>It will represent a collection of games</p>
{% endblock content %}